# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Today I learned
email: georg@get83.de
description: >- # this means to ignore newlines until "baseurl:"
  This site is my way of sharing and remembering learnings I had during
  the ongoing development of web applications for fun and profit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://til.jaz-lounge.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Georg_Tavonius
github_username:  Calamari
contactme: http://www.tavonius.de
default_share_text: Today I learned something cool on

meta:
  description: >-
    Here you see some smaller and bigger tips and tricks that did save me time and
    optimized my development processes already and might you to in the future.
  keywords: "elixir, ruby, python, development, programming, tips, tricks"

paginate: 20
paginate_path: '/page/:num/'
# pagination:
#   enabled: true
#   per_page: 20
#   permalink: '/page/:num/'
#   sort_reverse: true

github:
  repo: https://github.com/Calamari/til-static

permalink: /:categories/:slug

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

sass:
  style: compressed

# jekyll-archives:
#   enabled:
#     - categories
#   layout: category_index
#   permalinks:
#     # year: '/:year/'
#     # month: '/:year/:month/'
#     # day: '/:year/:month/:day/'
#     # tag: '/tag/:name/'
#     category: '/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
